function SondaACE = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  SONDAACE = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  SONDAACE = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  SondaACE = importfile("/home/vladimir/Escritorio/Señales/Utils4SP/Datasets/Sonda_ACE.txt", [93, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 211025 14:53:45

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [93, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "         ";

% Specify column names and types
opts.VariableNames = ["DateTime", "Bx_nt", "By_nt", "Bz_nt", "Var5", "Var6", "Var7"];
opts.SelectedVariableNames = ["DateTime", "Bx_nt", "By_nt", "Bz_nt"];
opts.VariableTypes = ["datetime", "double", "double", "double", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var5", "Var6", "Var7"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var5", "Var6", "Var7"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "DateTime", "InputFormat", "dd-MM-yyyy HH:mm:ss.SSS");
opts = setvaropts(opts, ["Bx_nt", "By_nt", "Bz_nt"], "ThousandsSeparator", ",");

% Import the data
SondaACE = readtable(filename, opts);

end